version: "3.8"
services:
  belugasnooze_rust_pi_client:
    image: belugasnooze_rust_pi_client:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID}
        - DOCKER_GUID=${DOCKER_GUID}
        - DOCKER_TIME_CONT=${DOCKER_TIME_CONT}
        - DOCKER_TIME_CITY=${DOCKER_TIME_CITY}
    container_name: belugasnooze_rust
    env_file: .env
    volumes:
       - $HOME/belugasnooze_rust/db_data:/db_data
       - /ramdrive/ip.addr:/ip_address/ip.addr:ro
    cap_drop:
      - all
    group_add:
      - ${DOCKER_GPIO}
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    devices:
    - "/dev/gpiomem"
    - "dev/gpiochip0"
    networks:
      - belugasnooze_rust_net
    deploy:
      resources:
        limits:
          memory: 96M
networks:
  belugasnooze_rust_net:
    name: belugasnooze_rust_net